const data = {
  add_offset_to_routes: true,
  color_and_size_stops_by_count: true,
  color_and_size_segments_by_count: true,
  color_by_route: true,
  color_by_agency: false,
  show_stop_data: true,
  show_segment_data: true,
  show_route_data: true,
  loading: false,
  sim_speed_min:-50,
  sim_speed:20,
  sim_speed_max:100,
  sim_time_min:1.0,
  sim_time:1.0,
  sim_time_max:1.0,
  spreading_sim_time_min:0.0,
  spreading_sim_time:0.0,
  spreading_sim_time_max:0.0,
  show_footer:true,
  show_data_select:true,
  tail_length_min:1.0,
  tail_length:30,
  tail_length_max:600,
  use_shapes:true,
  durations:[60, 300, 600, 1800, 3600],
  duration:600,
  anim_stopped:true,
  anim_data:{},
  anim_data_ready:false,
  data_loadable:false,
  anim_visible:true,
  spreading_stopped:true,
  spreading_data:{},
  spreading_data_ready:false,
  spreading_visible:true,
  spreading_lat : null,
  spreading_lon : null,
  spreading_sim_speed_min:-50,
  spreading_sim_speed:20,
  spreading_sim_speed_max:100,
  stats: null,
  tabToShow: null
};

export default data;